### ISSUE TITLE
Incorrect test

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/boilerplate-advancednode#3]
**[The exercise](https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/create-new-middleware):** Redirect to home page

**About the [test](https://github.com/freeCodeCamp/curriculum/blob/cfa99ef3cb7d1c00e47d0a7040528382dd35d5c2/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json#L255):** The  requires the final page to contain the text `/Home page/gi` (At Line 255/char 103)

**The problem:**

- The [home page template file](https://github.com/freeCodeCamp/boilerplate-advancednode/blob/gomix/views/pug/index.pug) doesn't contain 'home page'

- Neither the values of dynamic variables: [{title: 'Hello', message: 'Please login'});](https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/use-a-template-engines-powers)

**Update:** duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/18201#issuecomment-425758234

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
